### PR TITLE
Manage templates path

### PR DESCRIPTION
**Pull request by tboulogne**

### CODE REVIEW

**Comment by synw** [comment]
It would be better to have both the project templates dirs and the apps templates dirs

We can use `settings.TEMPLATES[0]['DIRS']` to get the project templates dirs paths and `django.template.loaders.app_directories.get_app_template_dirs` to check for `instant/handlers` folders in app templates dirs

**Comment by tboulogne** [comment]
yep looks clean :)

**Comment by synw** [comment]
Done. The handlers can now be located either in the project templates dirs or in the apps templates dirs, closing. @tboulogne : thanks for the help

**Comment by tboulogne** [comment]
@synw thanks for this good django extension :). You welcome.

**Pull request closed without merging**
