### PR TITLE
django.core.urlresolvers removed in Django 2

### PR DESCRIPTION
**Pull request by tboulogne**
Hello,

find this small contribution to improve python 3 compat.
```
django.core.urlresolvers
```

change to

```
django.urls
```

regards

### CODE REVIEW

**Comment by synw** [comment]
Good catch! Thank you for this contribution but it appears that it is a Django 2 related issue, not a Python 3 one. Would you mind changing you PR to test vs Django 2 instead of Python 3?

**Comment by tboulogne** [comment]
oh my bad !

Yes it's django 2 related. Let's me change this.

**Comment by tboulogne** [comment]
Ok change this for django 2.0

**Comment by synw** [comment]
Thanks a lot!

**Pull request merged**
